---
title: "Assignment 2"
author: "Claire Chang Liu and Noriko Magara"
date: "Oct. 23, 2015"
output: pdf_document
bibliography: EV_proposal.bib
---

For the collaborative research project, we will work on adoption of electric vehicles in the U.K., 
focusing on identifying the potential buyers which hopefully helps the U.K. government to differentiate EV promoting strategies by target groups. 
This document presents detailed proposal for our project.

## Background

As a part of the efforts to cope with the climate change, countries have been trying to reduce greenhouse gas (GHG) emissions. 
Considering the fact that the large portion of GHG emission is attributed to road traffic [@EC_climate], reducing the emission from vehicles is an important issue for many industrialized countries.

Several types of low emission vehicles have been invented and released into the world as listed below [@USDOE].

* Hybrid electric vehicles (HEVs), which use both a conventional inner combustion engine (e.g. gasoline engine) and an electric motor, are the early generation of the low emission vehicles. 
HEVs store electric powers in a battery from braking and the inner combustion engine, which are normally lost in conventional vehicles. 
Thus, HEVs have better fuel efficiency and less emission compared to the conventional vehicles.
* Plug-in hybrid electric vehicles (PHEVs) are the improved version of HEVs. 
PHEVs have a smaller inner combustion engine and more powerful batteries that can be charged by plugging into charging infrastructures, as well as the energy captured from braking and the inner combustion engine. 
Thus, PHEVs have further better fuel efficiency and less emission compared to HEVs.
* Electric Vehicles (EVs) are the most recent generation of the low emission vehicles, which powered only by an electric motor. 
The batteries that drive the motors are charged by plugging into charging infrastructures. 
Because EVs do not use inner combustion engines at all, they make no emission when they drive.

From the environmental point of view, EVs are the ideal type of vehicles. 
However, because of many reasons, the adoption rates of EVs are not as high as the desirable level. 
One of the biggest reasons is the costs. 
Although some articles report that EVs are cheaper than conventional vehicles in long-term thanks to no fuel costs [e.g. @Herron2015web], people tend to refrain from buying EVs because of the high purchase prices.
Also, current technical standards such as battery capacities (maximum driving distance with one-time charging) are pointed out to be an obstacle to the widespread EV adoption [@lieven2011will]. 
Availability of charging stations matters as well [@ChargingStation].
 
Aiming to promote EVs and other types of low emission vehicles, governments have been taking various kinds of means such as financial incentives to owners, R&D grants, installation of charging infrastructures. 
In order to maximize the performance of those governments' efforts, and thus to accelerate low emission vehicle adoption, it is crucial to **identify the characteristics of the potential EV buyers**, and **reasons that makes those potential buyers to choose EVs over conventional vehicles**.

This study will focus on EVs, which is the most recent generation of low emission vehicles and thus not many researches have made so far compared to other types of sustainable vehicles.


## Literature Review

Previous studies have examined various factors that influence consumers' choice.

At a macro level, the relationship between demographic characteristics and EV adoption has been analyzed. For instance, 
@countrycomparison identify financial incentives, the prevalence of charging stations, and the presence of a local EV manufacturer as the relevant factors, using data on 30 countries. Interestingly, however, they do not find socio-economic variables to be good predicators of a country's EV adoption level. Another macro-level study divides Finland into grids with different socio-economic characteristics and finds that "the income and education level, the amount of families with children and the average size of the residences" (p. 459) are related to the region-level or neighborhood-level adoption rate of EVs [@Finland2013].

At a micro level, motivations and individual characteristics that affect individual choice are studied. 
@egbue2012barriers explores characteristics of potential EV buyers through a survey targeting current conventional vehicle owners, which asked their opinions, perceptions, and attitudes towards EVs, besides socio-economic attributes. 
Using 481 observations gained from the web-based survey, the authors performs chi-square analyses and find out that different groups of people have different stances towards EVs. 
For instance, likelihood to purchase an EV ("How likely would you be to consider purchasing a vehicle that uses alternative fuel?") differs by gender, education level, age, and income of respondents. 
In addition, based on the survey questions regarding the respondents' concerns, the authors reveal that more than a quarter of them were unsure about the safety of EVs. 
Therefore, they concluds that people with better knowledge about EVs are more likely to purchase one.  

There are not many studies that observed people who actually bought an EV, possibly resulting from the small adoption rate. 
However, a similar study for another type of low emission vehicle may be helpful to think about the motivations that push people to purchase one. 
@ozaki2011going analyze consumers' motivations to purchase an HEV.
Based on a survey data of HEV owners, the authors discovers that people bought an HEV motivated by environmental benefits, as well as personal economic benefits. 
As a policy implication, advertisements to the public are suggested along with financial incentives to the owners.

In addition, possible policy options to promote low emission vehicle adoption are also covered in several articles.
For an example of PHEVs, @skerlos2010targeting discuss an effective way to allocate government's financial resources. 
Currently, the U.S. federal government provides uniform tax credits to all PHEV owners aiming to expand share of PHEVs in the car market. 
Considering the social benefits of PHEVs including reduced GHG emission, air pollution abatement, increased energy security, the authors argue that the tax credits could have worked better if the government differentiated the incentives depending on consumers' purchasing power and geographical locations. 
As for the purchasing power, more credits to lower income individuals and fewer to higher income ones may have increased PHEV adoption, considering that current level of financial incentives may not be enough for low income people, while high income people would have bought one anyways with less or no financial incentives. 
As for the environmental benefit, PHEV owners in highly populated areas should have received larger credits because one unit reduction of pollution delivers larger benefits (i.e. affects more people). 
It would also be ideal to promote PHEVs in the areas where the electric powers are generated from alternative sources rather than thermal powers that use fossil fuels.

Since policies of financial incentives are the most common one, @givinggreen compare a number of policies to promote EV in different US states. Mainly focusing on the efficacy of sales tax waivers and income tax credits, they find that the former is "associated with ten-fold increase in hybrid sales" (p.1) and that tax incentives are generally more effective than non-tax incentives. 
Thus, both to identifying the characteristics of potential buyers and to design government interventions targeting those individuals are the essential strategies to promote low emission vehicles. 

Regarding EV adoption, more detailed researches that focus on EVs are needed. 
In particular, not many studies on the relationship between EV adoption and the micro level, individual motivations and characteristics have made partly due to the lack of survey data on people's attitudes towards EVs that covers both those who buy (or are willing to buy) and those who do not. 
In this study, we will examine the micro level relationship using a recent dataset from the U.K.


## Methodology
The dataset we use in this research will be ["Opinions and Lifestyle Survey, Electric Vehicles Module, February 2014 and February 2015"](https://discover.ukdataservice.ac.uk/Catalogue/?sn=7571&type=Data%20catalogue) conducted by the Social Survey Division of Office for National Statistics of the Great Britain [@UKDATA]. 
This module is part of the "Opinions and Lifestyle Survey" and is conducted on the behalf of the Department for Transport. 
Population surveyed is adults, aged 16 or over, living in private households in Great Britain; and the sampling method is multi-stage stratified random sampling. 
The total sample size is 1996, 962 cases from 2014 and 1034 cases from 2015.
EVs mentioned in this survey refer to vehicles that run solely on electricity or are plug-in hybrids (excluding hybrids which are not plugged into an electricity supply).

Note that [registration](http://ukdataservice.ac.uk/get-data/how-to-access/registration) is required to download the dataset from the U.K. Data Service website above.
After logging in and agreeing with the terms of conditions, the dataset is available for download in CSV or other format.
The registration process may take a few days. 
However, other documents (e.g. questionnaire, brief summary) are available at the link above without registration.

The survey is consisted of mainly two sets of variables, core questions (i.e. questions related to buying an electric car or van) and demographic variables. Core questions that are of our interest are:

1. Which statement best describes your attitude towards buying an electric car?
2. What would put you off buying an electric car or van?
3. What would encourage you to buy an electric car or van?

(For the second and third question, there are two same questions asked solely on financial considerations, which we could explore in more details.)

Demographic variables that are of our interest are:

1. Sex
2. Age
3. Government office region
4. Level of education
5. Gross annual income
6. Employment status
7. Occupation status
8. Legal marital status
9. Household size
10. Number of dependent children in the household
11. Car/van ownership
12. Ownership of accommodation
13. Holding a valid driver's license or not
14. Frequency of travelling by private car/van
15. Being disabled or not

We are interested in the potentially different attitudes and priorities of different groups and in identifying potential buyers of EVs as well as obstacles preventing EV consumption. (To better understand the regional differences, if there are, we will look closer into regional policies or aggregate-level characteristics of Great Britain.) Therefore, we will be using the three core questions as dependent variables and demographic variables as independent variables. We will also be primarily using data from 2015, and might draw on data from 2014 in case of a need for contrast or support. 

As our dependent variables are all categories variables, **multinomial logistic regression** will be adopted:

$$\ln{\frac{Pr(Y_i=1)}{Pr(Y_i=K)}}=\beta_{0,1} + \beta_{1,1} x_{1,i} + \beta_{2,1} x_{2,i} + \dots = \boldsymbol{\beta_1 \cdot x_i}$$
$$\ln{\frac{Pr(Y_i=2)}{Pr(Y_i=K)}}=\boldsymbol{\beta_2 \cdot x_i}$$
$$\vdots$$
$$\ln{\frac{Pr(Y_i=K-1)}{Pr(Y_i=K)}}=\boldsymbol{\beta_{K-1} \cdot x_i}$$

Where $Pr(Y_i=1)$ to $Pr(Y_i=K)$ are the probabilities that the *i*th person is classified into the first category to the *K*th category, and $\boldsymbol{x_i}$ is a vector of the *i*th person's independent variables, i.e. the individual's characteristics in our study. 

By converting the log odds into probabilities, we will obtain the probability of the *i*th person being classified into the *J*th category (e.g. buying an EV) depending on his/her personal characteristics. 
For the *K*th category (the category used as a reference), the predicted probability is calculated by the second formula.

$$Pr(Y_i=J)=\frac{e^{\boldsymbol{\beta_J \cdot x_i}}} {1 + \sum_{k=1}^{K-1} e^{\boldsymbol{\beta_k \cdot x_i}}}$$

$$Pr(Y_i=K)=\frac{1} {1 + \sum_{k=1}^{K-1} e^{\boldsymbol{\beta_k \cdot x_i}}}$$

Thus, we are expecting to see different predicted probabilities of showing certain attitudes or making certain decisions for different demographic groups, which will provide some useful information for the policy makers to create efficient means to promote EVs.


Specifically, based on previous literature, there are several hypotheses as following:

1. Older generations are more likely to accept EVs.
2. Higher education leads to higher acceptance of EVs.
3. Higher income leads to higher acceptance of EVs.
4. Households with children are more likely to buy EVs.

Unfortunately, not much research has been done on the specific barriers or drivers of people buying EVs, so we are not able to form any hypotheses with the other two dependent variables. With that part, this study will be mostly exploratory.



## Conclusions

From the analysis described above, we will identify the following two things in this study:

1. Individual-level characteristics of possible EV buyers in the U.K.
2. Key factors that makes people buy or not buy an EV

In addition, some possible policy options that the U.K. government could take to increase EV adoption will be derived by targeting the identified characteristics and key factors. 


## Reference